apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: nginx-simulated-scaler
  namespace: nginx-simulated
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-simulated-deployment

  minReplicaCount: 1
  maxReplicaCount: 10
  pollingInterval: 15

  triggers:
  - type: prometheus
    metricType: AverageValue
    metadata:
      query: |
        sum(rate(nginx_http_requests_total{job="nginx-simulated-service", namespace="nginx-simulated"}[1m]))
      threshold: "5"
      serverAddress: http://prometheus-stack-kube-prom-prometheus.monitoring.svc.cluster.local:9090

  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 60
