apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: nginx-simulated-scaler
  namespace: nginx-simulated
spec:
  scaleTargetRef:
  triggers:
  - type: prometheus
    metadata:
      query: |
        sum(rate(nginx_http_requests_total{job="nginx-simulated-service", namespace="nginx-simulated"}[5m])) / 
        count(kube_pod_info{pod=~"nginx-simulated-deployment.*", namespace="nginx-simulated"})
      threshold: "5"
      serverAddress: http://prometheus-stack-kube-prom-prometheus.monitoring.svc.cluster.local:9090
