apiVersion: v1
kind: Service
metadata:
  name: nginx-simulated-service
  namespace: nginx-simulated
  labels:
    app: nginx-simulated
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9113"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  selector:
    app: nginx-simulated
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 9113
    targetPort: 9113
    protocol: TCP
    name: metrics
