apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-simulated-monitor
  namespace: nginx-simulated
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: nginx-simulated
  namespaceSelector:
    matchNames:
    - nginx-simulated
  endpoints:
  - port: metrics
    path: /metrics
    interval: 15s
