apiVersion: v1
kind: Service
metadata:
  name: nginx-simulated-service
  namespace: nginx-simulated
  labels:
    app: nginx-simulated
spec:
  type: ClusterIP
  selector:
    app: nginx-simulated
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
