apiVersion: v1
kind: ServiceAccount
metadata:
  name: porkbun-webhook
  namespace: cert-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: porkbun-webhook
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["cert-manager.io"]
  resources: ["challenges", "orders"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: porkbun-webhook-binding
roleRef:
  apiGroup: rbac.authorization.io
  kind: ClusterRole
  name: porkbun-webhook
subjects:
- kind: ServiceAccount
  name: porkbun-webhook
  namespace: cert-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-webhook-porkbun
  namespace: cert-manager
spec:
  selector:
    matchLabels:
      app: porkbun-webhook
  template:
    metadata:
      labels:
        app: porkbun-webhook
    spec:
      serviceAccountName: porkbun-webhook
      containers:
      - name: porkbun-webhook
        image: mdonoughe/porkbun-webhook:latest
        imagePullPolicy: IfNotPresent
        args:
        - --group-name=porkbun.acme.solver
        - --solver-name=porkbun-solver
        env:
        - name: PORKBUN_API_KEY
          valueFrom:
            secretKeyRef:
              name: porkbun-cert-manager-secret
              key: api-key
        - name: PORKBUN_API_SECRET
          valueFrom:
            secretKeyRef:
              name: porkbun-cert-manager-secret
              key: secret-key
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cert-manager-webhook-porkbun
  namespace: cert-manager
spec:
  selector:
    app: porkbun-webhook
  ports:
  - port: 443
    targetPort: 8080
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-porkbun
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: joshua.mcbeth@gmail.com
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
    - dns01:
        webhook:
          groupName: porkbun.acme.solver
          solverName: porkbun-solver
